apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jason-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/jason-nginx-webapp
    repoURL: https://github.com/jason-leong-ihpc/argocd-demo.git
    targetRevision: HEAD
  destination:
    namespace: jason-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
